import type { Language } from "./portfolio-copy";

export const freelanceCopy = {
  en: {
    nav: { home: "Home", services: "Services", websites: "Website examples", work: "Career work", contact: "Contact" },
    common: {
      demo: "CONCEPT / DEMO",
      planned: "PLANNED CONCEPT",
      languageLabel: "Choose language",
      availability: "Freelance enquiries open",
      email: "Discuss a project",
    },
    services: {
      eyebrow: "FREELANCE WEBSITE DEVELOPMENT",
      title: "Practical websites, designed and shipped by one independent builder.",
      intro: "I design and build fast, responsive websites for small businesses, professionals, and independent brands. I can handle the process from initial layout and development through deployment, domain setup, and basic analytics.",
      examplesCta: "View website examples",
      contactCta: "Tell me about your website",
      sectionLabel: "TYPICAL PROJECTS",
      sectionTitle: "A clear scope for the project you actually need.",
      sectionIntro: "Each engagement starts with the audience, content, pages, and primary action—then scales to the simplest build that can meet the goal.",
      categories: [
        { title: "Landing page", body: "A focused one-page marketing site for a launch, campaign, service, or offer with a direct path to action." },
        { title: "Business website", body: "A small multi-page site that makes services, location, trust signals, and contact information easy to find." },
        { title: "Portfolio website", body: "A professional personal or creative portfolio that makes the work, experience, and value clear." },
        { title: "Website redesign", body: "A thoughtful modernization of an existing site, including its mobile experience and primary conversion paths." },
        { title: "Custom website / automation", body: "A scoped web tool, integration, form, dashboard, or workflow when the project needs more than static pages." },
      ],
      includedLabel: "PRACTICAL FOUNDATIONS",
      includedTitle: "The essentials needed to launch well.",
      included: [
        "Responsive and mobile-friendly implementation",
        "Domain connection and deployment setup",
        "Basic on-page SEO and social metadata",
        "Basic analytics integration",
        "Contact forms or lead-capture flows",
        "A clear handover and maintenance plan",
      ],
      processLabel: "HOW A PROJECT MOVES",
      processTitle: "One clear path from idea to launch.",
      process: [
        { step: "Clarify", body: "We define the audience, the pages, the main action, and what a successful launch should do." },
        { step: "Design", body: "I shape the content hierarchy and visual direction around your business—not a generic template." },
        { step: "Build", body: "I develop the responsive site, add agreed integrations, and test the important paths." },
        { step: "Launch & maintain", body: "I connect the domain, deploy the site, check analytics, and agree on practical follow-up support." },
      ],
      boundary: "For complex e-commerce, large member platforms, or payment-heavy systems, I will be direct about the scope and whether a different setup is a better fit.",
      finalTitle: "Need a new website, redesign, landing page, or small automation?",
      finalBody: "Tell me what you are trying to achieve, what already exists, and your preferred timeline. I’ll reply with a practical next step.",
    },
    websites: {
      eyebrow: "WEBSITE EXAMPLES",
      title: "Website concepts for small businesses and independent professionals.",
      intro: "These examples show how I approach layout, content hierarchy, responsive development, and conversion paths across different kinds of businesses.",
      disclaimer: "These are concept and demo projects created to demonstrate design and development capability. They are not presented as commissioned client work.",
      servicesCta: "View web services",
      contactCta: "Discuss a website",
      sectionLabel: "REUSABLE DEMOS",
      sectionTitle: "Designed to feel specific. Built to adapt.",
      viewDemo: "Open demo",
      plannedNote: "A reusable demo direction planned for the next portfolio release.",
      items: [
        { slug: "cafe", type: "Cafe", name: "Northstar Coffee", body: "Menu, location, opening hours, and a direct ordering path for an independent cafe.", accent: "amber" },
        { slug: "restaurant", type: "Restaurant", name: "Serein Table", body: "An editorial dining experience designed around discovery and reservations.", accent: "coral" },
        { slug: "law-firm", type: "Professional services", name: "Aster & Rowe", body: "A calm legal-services site with clear expertise and consultation paths.", accent: "blue" },
        { slug: "shop", type: "Local shop", name: "Field Supply", body: "A product catalogue for browsing and direct ordering without a heavy commerce system.", accent: "green" },
        { slug: null, type: "Personal portfolio", name: "Independent Practice", body: "A flexible portfolio structure for a consultant, creative, or specialist.", accent: "violet" },
        { slug: null, type: "Small business landing page", name: "Focused Launch", body: "A direct, single-page route from business value to enquiry or lead capture.", accent: "red" },
      ],
      capabilityLabel: "Each active demo is",
      capabilities: ["Responsive", "Semantic HTML", "Metadata", "Rebrandable"],
      finalTitle: "Have a business that needs a clearer web presence?",
      finalBody: "I can adapt an existing direction or design a focused website around your own content, audience, and goals.",
    },
  },
  my: {
    nav: { home: "မူလစာမျက်နှာ", services: "ဝန်ဆောင်မှု", websites: "Website နမူနာ", work: "လုပ်ဆောင်မှုများ", contact: "ဆက်သွယ်ရန်" },
    common: {
      demo: "CONCEPT / DEMO",
      planned: "စီစဉ်ထားသော နမူနာ",
      languageLabel: "ဘာသာစကား ရွေးချယ်ရန်",
      availability: "Freelance အလုပ်များ လက်ခံနေပါသည်",
      email: "Project အကြောင်း ဆွေးနွေးရန်",
    },
    services: {
      eyebrow: "FREELANCE WEBSITE တည်ဆောက်မှု",
      title: "လက်တွေ့အသုံးဝင်တဲ့ website တွေကို လွတ်လပ်စွာ တစ်ဦးတည်း ဒီဇိုင်းဆွဲ၊ တည်ဆောက်ပြီး အသုံးပြုနိုင်အောင် ထုတ်ပေးပါတယ်။",
      intro: "အသေးစားလုပ်ငန်း၊ ကျွမ်းကျင်ပညာရှင်နဲ့ ကိုယ်ပိုင် brand တွေအတွက် မြန်ဆန်ပြီး ဖုန်း၊ ကွန်ပျူတာတိုင်းမှာ ကြည့်ကောင်းတဲ့ website တွေ ဒီဇိုင်းဆွဲတည်ဆောက်ပေးပါတယ်။ အစပိုင်း layout ကနေ development၊ deployment၊ domain ချိတ်ဆက်ခြင်းနဲ့ အခြေခံ analytics အထိ တာဝန်ယူနိုင်ပါတယ်။",
      examplesCta: "Website နမူနာများ ကြည့်ရန်",
      contactCta: "သင့် website အကြောင်း ပြောပြပါ",
      sectionLabel: "ပုံမှန် PROJECT အမျိုးအစားများ",
      sectionTitle: "အမှန်တကယ်လိုအပ်တဲ့ project အတွက် ရှင်းလင်းတဲ့ scope။",
      sectionIntro: "Audience၊ content၊ page အရေအတွက်နဲ့ အဓိက action ကို အရင်ဆုံးသတ်မှတ်ပြီး ရည်ရွယ်ချက်ကို ဖြည့်ဆည်းနိုင်တဲ့ အရိုးရှင်းဆုံး build ကို ရွေးချယ်ပါတယ်။",
      categories: [
        { title: "Landing page", body: "Launch၊ campaign၊ service သို့မဟုတ် offer တစ်ခုအတွက် တိုက်ရိုက် action လုပ်နိုင်တဲ့ one-page marketing site။" },
        { title: "Business website", body: "ဝန်ဆောင်မှု၊ တည်နေရာ၊ ယုံကြည်မှုအထောက်အထားနဲ့ ဆက်သွယ်ရန်အချက်အလက်တွေ ရှင်းလင်းတဲ့ multi-page site အသေးစား။" },
        { title: "Portfolio website", body: "လုပ်ဆောင်မှု၊ အတွေ့အကြုံနဲ့ ပေးနိုင်တဲ့တန်ဖိုးကို ရှင်းလင်းစေတဲ့ professional personal သို့မဟုတ် creative portfolio။" },
        { title: "Website redesign", body: "ရှိပြီးသား site ကို ခေတ်မီစေပြီး mobile experience နဲ့ အဓိက conversion path တွေကို ပိုရှင်းစေခြင်း။" },
        { title: "Custom website / automation", body: "Static page ထက်ပိုလိုတဲ့အခါ scope သတ်မှတ်ထားတဲ့ web tool၊ integration၊ form၊ dashboard သို့မဟုတ် workflow။" },
      ],
      includedLabel: "စတင်အသုံးပြုဖို့ လိုအပ်သော အခြေခံများ",
      includedTitle: "Website တစ်ခု ကောင်းကောင်းစတင်ဖို့ လိုအပ်တာများ။",
      included: [
        "ဖုန်းနှင့် ကွန်ပျူတာတွင် အဆင်ပြေသော responsive build",
        "Domain ချိတ်ဆက်ခြင်းနှင့် deployment setup",
        "အခြေခံ SEO နှင့် social metadata",
        "အခြေခံ analytics ချိတ်ဆက်မှု",
        "Contact form သို့မဟုတ် lead capture လမ်းကြောင်း",
        "ရှင်းလင်းသော လွှဲပြောင်းပေးမှုနှင့် maintenance အစီအစဉ်",
      ],
      processLabel: "PROJECT တစ်ခု လုပ်ဆောင်ပုံ",
      processTitle: "အကြံဉာဏ်ကနေ launch အထိ ရှင်းလင်းတဲ့ လမ်းကြောင်းတစ်ခု။",
      process: [
        { step: "ရှင်းလင်းသတ်မှတ်ခြင်း", body: "ဘယ်သူတွေအတွက်လဲ၊ ဘယ်စာမျက်နှာတွေလိုလဲ၊ အဓိကလုပ်ဆောင်ချက်နဲ့ အောင်မြင်မှုကို ဘယ်လိုသတ်မှတ်မလဲ ဆွေးနွေးပါတယ်။" },
        { step: "ဒီဇိုင်းဆွဲခြင်း", body: "Generic template တစ်ခုမဟုတ်ဘဲ လုပ်ငန်းနဲ့ကိုက်ညီတဲ့ အကြောင်းအရာအစီအစဉ်နဲ့ visual direction ကို တည်ဆောက်ပါတယ်။" },
        { step: "တည်ဆောက်ခြင်း", body: "ဖုန်း၊ ကွန်ပျူတာမှာ အဆင်ပြေတဲ့ site ကို တည်ဆောက်ပြီး သဘောတူထားတဲ့ integration တွေ ထည့်ကာ အရေးကြီးတဲ့ လမ်းကြောင်းတွေ စမ်းသပ်ပါတယ်။" },
        { step: "Launch နှင့် ထိန်းသိမ်းခြင်း", body: "Domain ချိတ်ဆက်၊ site ကို deploy လုပ်၊ analytics စစ်ဆေးပြီး နောက်ပိုင်းလိုအပ်မယ့် အကူအညီကို သဘောတူညီပါတယ်။" },
      ],
      boundary: "ရှုပ်ထွေးတဲ့ e-commerce၊ member platform အကြီးစား သို့မဟုတ် payment အများကြီးပါဝင်တဲ့ system များအတွက် scope ကို ပွင့်ပွင့်လင်းလင်း ဆွေးနွေးပြီး အခြား setup ပိုသင့်တော်မတော် ပြောပြပါမယ်။",
      finalTitle: "Website အသစ်၊ redesign၊ landing page သို့မဟုတ် automation အသေးစား လိုအပ်ပါသလား။",
      finalBody: "လုပ်ချင်တဲ့ရည်ရွယ်ချက်၊ လက်ရှိရှိပြီးသားအရာနဲ့ လိုချင်တဲ့အချိန်ကို ပြောပြပါ။ လက်တွေ့ကျတဲ့ နောက်တစ်ဆင့်ကို ပြန်လည်အကြံပြုပါမယ်။",
    },
    websites: {
      eyebrow: "WEBSITE နမူနာများ",
      title: "အသေးစားလုပ်ငန်းနဲ့ ကိုယ်ပိုင်လုပ်ငန်းလုပ်ကိုင်သူတွေအတွက် website concept များ။",
      intro: "လုပ်ငန်းအမျိုးအစားမတူတဲ့ website တွေမှာ layout၊ အကြောင်းအရာအစီအစဉ်၊ ဖုန်းနဲ့ကွန်ပျူတာအတွက် development နဲ့ ဆက်သွယ်မေးမြန်းရန် လမ်းကြောင်းကို ဘယ်လိုတည်ဆောက်သလဲဆိုတာ ပြထားပါတယ်။",
      disclaimer: "ဒီအရာတွေဟာ design နဲ့ development လုပ်နိုင်မှုကို ပြသဖို့ ဖန်တီးထားတဲ့ concept နဲ့ demo project များဖြစ်ပြီး တကယ့် client မှ အပ်နှံထားတဲ့ project များအဖြစ် မတင်ပြထားပါ။",
      servicesCta: "Website ဝန်ဆောင်မှုများ",
      contactCta: "Website အကြောင်း ဆွေးနွေးရန်",
      sectionLabel: "ပြန်လည်အသုံးချနိုင်သော DEMO များ",
      sectionTitle: "လုပ်ငန်းနဲ့ ကိုက်ညီအောင် ဒီဇိုင်းဆွဲထားပြီး လိုအပ်သလို ပြင်ဆင်နိုင်ပါတယ်။",
      viewDemo: "Demo ဖွင့်ရန်",
      plannedNote: "နောက် portfolio update အတွက် စီစဉ်ထားတဲ့ ပြန်လည်အသုံးချနိုင်သော demo direction တစ်ခုပါ။",
      items: [
        { slug: "cafe", type: "Cafe", name: "Northstar Coffee", body: "Menu၊ တည်နေရာ၊ ဖွင့်ချိန်နဲ့ တိုက်ရိုက်မှာယူရန် လမ်းကြောင်းပါသော cafe website။", accent: "amber" },
        { slug: "restaurant", type: "Restaurant", name: "Serein Table", body: "စားသောက်ဆိုင်ကို ရှာဖွေသိရှိနိုင်ပြီး reservation လုပ်နိုင်ဖို့ ဒီဇိုင်းဆွဲထားတဲ့ website။", accent: "coral" },
        { slug: "law-firm", type: "Professional services", name: "Aster & Rowe", body: "ဝန်ဆောင်မှုကျွမ်းကျင်မှုနဲ့ consultation လမ်းကြောင်းတွေ ရှင်းလင်းတဲ့ ဥပဒေဝန်ဆောင်မှု website။", accent: "blue" },
        { slug: "shop", type: "ပြည်တွင်းအရောင်းဆိုင်", name: "Field Supply", body: "လေးလံတဲ့ e-commerce system မလိုဘဲ product ကြည့်ရှု၊ တိုက်ရိုက်မှာယူနိုင်တဲ့ catalogue။", accent: "green" },
        { slug: null, type: "ကိုယ်ပိုင် portfolio", name: "Independent Practice", body: "Consultant၊ creative သို့မဟုတ် ကျွမ်းကျင်ပညာရှင်အတွက် ပြင်ဆင်အသုံးပြုနိုင်တဲ့ portfolio structure။", accent: "violet" },
        { slug: null, type: "အသေးစားလုပ်ငန်း landing page", name: "Focused Launch", body: "လုပ်ငန်းတန်ဖိုးကနေ မေးမြန်းမှု သို့မဟုတ် lead capture အထိ တိုက်ရိုက်ပို့ပေးတဲ့ စာမျက်နှာတစ်ခု။", accent: "red" },
      ],
      capabilityLabel: "ဖွင့်ကြည့်နိုင်တဲ့ demo တစ်ခုစီမှာ",
      capabilities: ["Responsive", "Semantic HTML", "Metadata", "Brand ပြောင်းနိုင်"],
      finalTitle: "သင့်လုပ်ငန်းအတွက် ပိုရှင်းလင်းတဲ့ website လိုအပ်ပါသလား။",
      finalBody: "ရှိပြီးသား direction တစ်ခုကို ပြင်ဆင်နိုင်သလို သင့်အကြောင်းအရာ၊ audience နဲ့ ရည်ရွယ်ချက်ကို အခြေခံပြီး website အသစ်တစ်ခုလည်း ဒီဇိုင်းဆွဲနိုင်ပါတယ်။",
    },
  },
} as const satisfies Record<Language, unknown>;
