export type Language = "en" | "my";

export const portfolioCopy = {
  en: {
    nav: { work: "Work", services: "Services", websites: "Websites", about: "About", experience: "Experience", contact: "Contact", available: "Available for opportunities" },
    hero: {
      eyebrow: "Independent builder · Yangon / Remote",
      version: "Portfolio v1.1",
      kicker: "Data Analyst & Automation Engineer · Product Builder",
      titleLead: "I turn complex ideas into ",
      titleAccent: "systems that make sense.",
      body: "I turn messy data, workflows, and product questions into structured analysis, useful tools, and clearer decisions—combining business thinking with hands-on delivery.",
      workCta: "Explore selected work",
      cvCta: "Download CV",
      focus: ["Data systems", "Automated workflows", "Analytics products & applied AI"],
      processLabel: "HOW I WORK",
      processTitle: "From an unclear problem to a useful result.",
      process: [
        { title: "Clarify", body: "Find the real problem, the people affected, and what success should mean." },
        { title: "Build", body: "Turn the insight into a focused system, product, dashboard, or experience." },
        { title: "Prove", body: "Measure what changed, learn from real use, and improve the next version." },
      ],
      disciplines: ["BUSINESS ANALYSIS", "PRODUCT THINKING", "DATA & BI", "AI SYSTEMS", "UX DESIGN", "AUTOMATION", "BUSINESS ANALYSIS", "PRODUCT THINKING"],
    },
    freelance: {
      label: "FREELANCE WEB SERVICES",
      title: "I also build practical websites for small businesses and independent professionals.",
      body: "I can handle the work from layout and development through deployment, domain setup, basic SEO, analytics, and useful lightweight automation.",
      servicesCta: "View web services",
      examplesCta: "See website examples",
    },
    work: {
      label: "SELECTED WORK",
      title: "Evidence, not just output.",
      intro: "Projects are documented as decisions: the problem, my contribution, the working system, and what the evidence showed.",
      flagship: "FLAGSHIP PRODUCT",
      live: "LIVE · EN / MY",
      wispRole: "Product owner · Product analytics · AI & automation",
      wispLede: "A bilingual relationship self-insight product designed for Myanmar users.",
      wispBody: "I built the product end-to-end: the guided assessment, deterministic psychology logic, result wording, payment journey, analytics, authentication, AI-personalization architecture, and production delivery.",
      metrics: ["Tracked starts", "Completions", "Completion rate"],
      metricContext: "FUNNEL SNAPSHOT · AUGUST 2026 · NOT REAL-TIME",
      caseStudy: "Read full case study",
      liveProduct: "Open live product",
      evidenceLabel: "Wisp project evidence",
      proof: [
        { label: "A / THE PROBLEM", title: "Make psychology approachable, not clinical.", body: "Turn a sensitive and abstract topic into a private reflection experience without presenting the result as diagnosis or therapy." },
        { label: "B / MY CONTRIBUTION", title: "Whole-system ownership.", body: "Product flow, bilingual UX, result logic, data ownership, analytics, Google authentication, payments, admin operations, and deployment." },
        { label: "C / THE SYSTEM", title: "Working product, not a concept.", body: "React interfaces, Python/FastAPI services, SQLite data, Cloudflare delivery, and a secured VPS release workflow." },
        { label: "D / THE EVIDENCE", title: "101 → 70 → 8", body: "The tracked funnel snapshot records 101 starts, 70 completions, and 8 purchase requests—evidence that now guides iteration." },
      ],
      projects: [
        { type: "ANALYTICS SYSTEM · IN DEVELOPMENT", name: "Personal Intelligence Lab", role: "Data workflow design · Analysis · Product build", line: "A guided workspace that turns unfamiliar datasets into quality checks, prepared data, analysis, and decision-ready reports.", tools: ["Python", "FastAPI", "React", "Data profiling"] },
        { type: "APPLIED AI · WORKFLOW", name: "Category Classification", role: "Evaluation design · Classification · API workflow", line: "A repeatable classification workflow built around evaluation, explainable categories, and clear inference—not just a model demo.", tools: ["Python", "NLP", "Evaluation", "API design"] },
      ],
      viewBuild: "View build work",
    },
    capabilities: {
      label: "CAPABILITIES",
      title: "From ambiguity to a working system.",
      intro: "I’m most useful when a problem crosses functions and needs both structured thinking and hands-on execution.",
      items: [
        { title: "Data & decision systems", body: "Define useful KPIs, shape dashboards, and turn operational data into decisions people can act on." },
        { title: "Business & product analysis", body: "Turn unclear goals into requirements, user flows, priorities, process maps, and measurable outcomes." },
        { title: "Automation & applied AI", body: "Build controlled AI and automation features around a real user need, practical limits, and human review." },
      ],
    },
    about: {
      label: "ABOUT",
      title: "I connect human behavior, business questions, and technical systems.",
      paragraphs: [
        "I’m K3, a product-minded analyst and builder based in Yangon. My strongest work sits where software, data, and human behavior overlap—especially when the original problem is still messy.",
        "My LLB background trained me to examine evidence, structure arguments, and work through ambiguity. I now apply that thinking to product analysis, data systems, UX, automation, and applied AI.",
        "I care about clear interfaces, evidence over guesswork, and shipping a useful first version that can keep getting better.",
      ],
    },
    experience: {
      label: "EXPERIENCE & EDUCATION",
      title: "A practical path into analysis and product systems.",
      intro: "Formal study, people-facing work, verified training, and independent technical delivery all shape how I approach a problem.",
      items: [
        { year: "CURRENT", role: "Independent product builder", org: "Wisp Guide", detail: "Product strategy, UX, analytics, AI integration, authentication, deployment, and commercial flows." },
        { year: "2026", role: "Python Data Associate", org: "DataCamp · Certified", detail: "Validated practical Python and data-handling knowledge through DataCamp's associate certification." },
        { year: "2023", role: "Field interviewer", org: "Myanmar Survey Research", detail: "Collected structured responses in real environments and worked directly with research participants." },
        { year: "2018–19", role: "Customer service", org: "Byblos", detail: "Built an early foundation in communication, service, and understanding what people actually need." },
      ],
      education: "EDUCATION",
      degree: "LLB · Completed",
      educationBody: "Legal training strengthened research, evidence evaluation, structured reasoning, and communication.",
      credential: "VERIFIED CREDENTIAL · JUNE 25, 2026",
      certificate: "Python Data Associate",
      certifiedBy: "Certified by DataCamp",
      viewCertificate: "View certificate",
    },
    demos: {
      label: "BUSINESS WEBSITE CONCEPTS",
      title: "Realistic sites for real local businesses.",
      intro: "Reusable concepts—not throwaway mockups. Each can be rebranded and adapted into a focused client website quickly.",
      demoLabel: "CONCEPT / DEMO",
      viewConcept: "VIEW CONCEPT",
      allExamples: "View all website examples",
      tags: ["Responsive", "Semantic HTML", "Metadata"],
      items: [
        { slug: "cafe", type: "Hospitality", name: "Northstar Coffee", line: "A warm café concept with menu, location, hours, and order flow.", accent: "amber" },
        { slug: "restaurant", type: "Dining", name: "Serein Table", line: "An editorial restaurant experience built for discovery and reservations.", accent: "coral" },
        { slug: "law-firm", type: "Professional services", name: "Aster & Rowe", line: "A calm legal site with services, team profiles, and consultation paths.", accent: "blue" },
        { slug: "shop", type: "Local retail", name: "Field Supply", line: "A local-shop catalogue for product discovery and direct ordering.", accent: "green" },
      ],
    },
    services: {
      label: "SERVICES",
      title: "Independent, practical, and built around what you actually need.",
      intro: "I help small teams and businesses clarify a problem, improve a digital experience, or ship a focused solution.",
      items: ["Business websites & landing pages", "Website redesign & UX improvement", "Analytics dashboards & KPI design", "Business process & system analysis", "AI-assisted solutions", "Lightweight automation"],
      viewAll: "Explore freelance web services",
    },
    contact: {
      label: "CONTACT",
      title: "Available for analyst and product opportunities.",
      candidateLabel: "LOOKING FOR A CANDIDATE?",
      candidateTitle: "Review the work and evidence.",
      body: "I’m open to junior Business Analyst, Data Analyst, Product Analyst, and focused automation work in Yangon or remote.",
      clientLabel: "NEED A WEBSITE OR AUTOMATION?",
      clientTitle: "Tell me about your project.",
      clientBody: "For freelance work, contact me about a new website, redesign, landing page, or small automation project.",
      email: "Email me",
      viewWork: "View my work",
      discussProject: "Discuss a project",
      viewServices: "View services",
      cv: "Download CV",
      footerRole: "Data Analyst · Automation Engineer · Product Builder",
    },
  },
  my: {
    nav: { work: "လုပ်ဆောင်မှုများ", services: "ဝန်ဆောင်မှု", websites: "Website နမူနာ", about: "ကျွန်တော့်အကြောင်း", experience: "အတွေ့အကြုံ", contact: "ဆက်သွယ်ရန်", available: "အလုပ်အကိုင်များ လက်ခံနေပါသည်" },
    hero: {
      eyebrow: "လွတ်လပ်စွာ တည်ဆောက်ဖန်တီးသူ · ရန်ကုန် / Remote",
      version: "Portfolio v1.1",
      kicker: "Data Analyst & Automation Engineer · Product Builder",
      titleLead: "ရှုပ်ထွေးတဲ့ အကြံဉာဏ်တွေကို ",
      titleAccent: "နားလည်လွယ်တဲ့ စနစ်တွေအဖြစ် ပြောင်းလဲတည်ဆောက်ပါတယ်။",
      body: "ရှုပ်ထွေးနေတဲ့ data၊ workflow နဲ့ product မေးခွန်းတွေကို စနစ်တကျ ခွဲခြမ်းစိတ်ဖြာပြီး အသုံးဝင်တဲ့ tool တွေနဲ့ ပိုရှင်းလင်းတဲ့ ဆုံးဖြတ်ချက်တွေအဖြစ် ပြောင်းလဲပါတယ်။ Business thinking ကို လက်တွေ့တည်ဆောက်နိုင်စွမ်းနဲ့ ပေါင်းစပ်လုပ်ဆောင်ပါတယ်။",
      workCta: "ရွေးချယ်ထားတဲ့ လုပ်ဆောင်မှုများကို ကြည့်ရန်",
      cvCta: "CV ရယူရန်",
      focus: ["Data စနစ်များ", "အလိုအလျောက် workflow များ", "Analytics product နှင့် applied AI"],
      processLabel: "ကျွန်တော် အလုပ်လုပ်ပုံ",
      processTitle: "မရှင်းလင်းသေးတဲ့ ပြဿနာတစ်ခုကနေ အသုံးဝင်တဲ့ ရလဒ်တစ်ခုအထိ။",
      process: [
        { title: "ရှင်းလင်းသတ်မှတ်ခြင်း", body: "အဓိကပြဿနာ၊ သက်ရောက်မှုရှိသူတွေနဲ့ အောင်မြင်မှုကို ဘယ်လိုတိုင်းတာမလဲဆိုတာ အရင်ဆုံး သတ်မှတ်ပါတယ်။" },
        { title: "တည်ဆောက်ခြင်း", body: "ရရှိထားတဲ့ သိမြင်မှုကို အာရုံစိုက်ထားတဲ့ system၊ product၊ dashboard သို့မဟုတ် experience တစ်ခုအဖြစ် တည်ဆောက်ပါတယ်။" },
        { title: "အတည်ပြုခြင်း", body: "တကယ့်အသုံးပြုမှုက ဘာတွေပြောင်းလဲစေခဲ့လဲ တိုင်းတာပြီး နောက်ဗားရှင်းကို ပိုကောင်းအောင် ပြင်ဆင်ပါတယ်။" },
      ],
      disciplines: ["လုပ်ငန်းခွဲခြမ်းစိတ်ဖြာမှု", "PRODUCT THINKING", "DATA & BI", "AI စနစ်များ", "UX ဒီဇိုင်း", "အလိုအလျောက်လုပ်ဆောင်မှု", "လုပ်ငန်းခွဲခြမ်းစိတ်ဖြာမှု", "PRODUCT THINKING"],
    },
    freelance: {
      label: "FREELANCE WEBSITE ဝန်ဆောင်မှု",
      title: "အသေးစားလုပ်ငန်းတွေနဲ့ ကိုယ်ပိုင်လုပ်ငန်းလုပ်ကိုင်သူတွေအတွက် လက်တွေ့အသုံးဝင်တဲ့ website တွေကိုလည်း တည်ဆောက်ပေးပါတယ်။",
      body: "Layout ဆွဲခြင်း၊ development လုပ်ခြင်းကနေ deployment၊ domain ချိတ်ဆက်ခြင်း၊ အခြေခံ SEO၊ analytics နဲ့ လိုအပ်သလို ပေါ့ပါးတဲ့ automation ထည့်သွင်းခြင်းအထိ တာဝန်ယူနိုင်ပါတယ်။",
      servicesCta: "Website ဝန်ဆောင်မှုများ",
      examplesCta: "Website နမူနာများ",
    },
    work: {
      label: "ရွေးချယ်ထားသော လုပ်ဆောင်မှုများ",
      title: "အလုပ်ရလဒ်တင်မဟုတ်ဘဲ အထောက်အထားပါ။",
      intro: "Project တစ်ခုစီကို ပြဿနာ၊ ကျွန်တော့်တာဝန်ယူမှု၊ အလုပ်လုပ်နိုင်တဲ့ စနစ်နဲ့ ရရှိခဲ့တဲ့ အထောက်အထားတွေအဖြစ် တင်ပြထားပါတယ်။",
      flagship: "အဓိက PRODUCT",
      live: "LIVE · EN / MY",
      wispRole: "Product owner · Product analytics · AI & automation",
      wispLede: "မြန်မာအသုံးပြုသူများအတွက် ဖန်တီးထားတဲ့ နှစ်ဘာသာသုံး relationship self-insight product တစ်ခုပါ။",
      wispBody: "Guided assessment၊ သတ်မှတ်ထားတဲ့ psychology logic၊ result wording၊ payment journey၊ analytics၊ authentication၊ AI personalization architecture နဲ့ production delivery အထိ product တစ်ခုလုံးကို အစမှအဆုံး တည်ဆောက်ခဲ့ပါတယ်။",
      metrics: ["စတင်အသုံးပြုမှု", "ပြီးဆုံးမှု", "ပြီးဆုံးနှုန်း"],
      metricContext: "FUNNEL SNAPSHOT · AUGUST 2026 · REAL-TIME မဟုတ်ပါ",
      caseStudy: "Case study အပြည့်အစုံဖတ်ရန်",
      liveProduct: "Live product ကိုဖွင့်ရန်",
      evidenceLabel: "Wisp project အထောက်အထားများ",
      proof: [
        { label: "A / ပြဿနာ", title: "Psychology ကို clinical မဖြစ်ဘဲ နားလည်လွယ်အောင် ပြုလုပ်ခြင်း။", body: "ထိခိုက်လွယ်ပြီး မျက်နှာမူဖို့ခက်တဲ့ အကြောင်းအရာကို diagnosis သို့မဟုတ် therapy လို မတင်ပြဘဲ ကိုယ်တိုင်သီးသန့် ပြန်လည်သုံးသပ်နိုင်တဲ့ experience အဖြစ် ပြောင်းလဲခဲ့ပါတယ်။" },
        { label: "B / ကျွန်တော့်တာဝန်", title: "System တစ်ခုလုံးကို တာဝန်ယူတည်ဆောက်ခြင်း။", body: "Product flow၊ နှစ်ဘာသာ UX၊ result logic၊ data ownership၊ analytics၊ Google authentication၊ payments၊ admin operations နဲ့ deployment အထိ တာဝန်ယူခဲ့ပါတယ်။" },
        { label: "C / စနစ်", title: "Concept တင်မဟုတ်ဘဲ အလုပ်လုပ်နိုင်တဲ့ product။", body: "React interface၊ Python/FastAPI service၊ SQLite data၊ Cloudflare delivery နဲ့ လုံခြုံရေးပြုလုပ်ထားတဲ့ VPS release workflow ကို အသုံးပြုထားပါတယ်။" },
        { label: "D / အထောက်အထား", title: "101 → 70 → 8", body: "မှတ်တမ်းတင်ထားတဲ့ funnel snapshot အရ စတင်သူ 101 ယောက်၊ ပြီးဆုံးသူ 70 ယောက်နဲ့ ဝယ်ယူရန်တောင်းဆိုမှု 8 ခုရှိခဲ့ပြီး ဒီအချက်အလက်တွေက နောက်တစ်ဆင့်ပြင်ဆင်မှုကို လမ်းညွှန်ပေးပါတယ်။" },
      ],
      projects: [
        { type: "ANALYTICS SYSTEM · တည်ဆောက်ဆဲ", name: "Personal Intelligence Lab", role: "Data workflow design · Analysis · Product build", line: "မရင်းနှီးသေးတဲ့ dataset တွေကို quality check၊ ပြင်ဆင်ထားတဲ့ data၊ analysis နဲ့ ဆုံးဖြတ်ချက်ချနိုင်တဲ့ report အဖြစ် ပြောင်းပေးမယ့် guided workspace တစ်ခုပါ။", tools: ["Python", "FastAPI", "React", "Data profiling"] },
        { type: "APPLIED AI · WORKFLOW", name: "Category Classification", role: "Evaluation design · Classification · API workflow", line: "Model demo တစ်ခုတင်မဟုတ်ဘဲ evaluation၊ ရှင်းပြနိုင်တဲ့ category တွေနဲ့ တိကျတဲ့ inference အပေါ် အခြေခံထားတဲ့ ထပ်ခါတလဲလဲ အသုံးပြုနိုင်သော classification workflow တစ်ခုပါ။", tools: ["Python", "NLP", "Evaluation", "API design"] },
      ],
      viewBuild: "တည်ဆောက်ထားမှုကို ကြည့်ရန်",
    },
    capabilities: {
      label: "လုပ်ဆောင်နိုင်မှုများ",
      title: "မရှင်းလင်းမှုကနေ အလုပ်လုပ်နိုင်တဲ့ စနစ်တစ်ခုအထိ။",
      intro: "လုပ်ငန်းကဏ္ဍအများအပြား ဆက်စပ်နေပြီး စနစ်တကျတွေးခေါ်မှုနဲ့ လက်တွေ့တည်ဆောက်မှု နှစ်ခုစလုံးလိုအပ်တဲ့ ပြဿနာတွေမှာ ကျွန်တော် အကောင်းဆုံး ကူညီနိုင်ပါတယ်။",
      items: [
        { title: "Data & decision systems", body: "အသုံးဝင်တဲ့ KPI တွေကို သတ်မှတ်ပြီး dashboard တွေ တည်ဆောက်ကာ operational data ကို လက်တွေ့ဆုံးဖြတ်ချက်တွေအဖြစ် ပြောင်းလဲပါတယ်။" },
        { title: "Business & product analysis", body: "မရှင်းလင်းသေးတဲ့ ရည်မှန်းချက်တွေကို requirement၊ user flow၊ process map၊ priority နဲ့ တိုင်းတာနိုင်တဲ့ outcome တွေအဖြစ် ပြောင်းလဲပါတယ်။" },
        { title: "Automation & applied AI", body: "တကယ့်အသုံးပြုသူတွေ လိုအပ်တာကို အခြေခံပြီး AI နဲ့ automation feature တွေ ဘာလုပ်နေတယ်ဆိုတာ လူက နားလည်နိုင်၊ စစ်ဆေးနိုင်ပြီး လိုအပ်ရင် ပြင်ဆင်နိုင်အောင် တည်ဆောက်ပါတယ်။" },
      ],
    },
    about: {
      label: "ကျွန်တော့်အကြောင်း",
      title: "လူတွေရဲ့ အပြုအမူ၊ လုပ်ငန်းဆိုင်ရာ မေးခွန်းတွေနဲ့ နည်းပညာစနစ်တွေကို ချိတ်ဆက်တည်ဆောက်ပါတယ်။",
      paragraphs: [
        "ကျွန်တော်က K3 ပါ။ ရန်ကုန်အခြေစိုက် product-minded analyst နဲ့ builder တစ်ယောက်ဖြစ်ပါတယ်။ Software၊ data နဲ့ လူတွေရဲ့ အပြုအမူ ဆုံတဲ့နေရာ၊ အထူးသဖြင့် မူလပြဿနာက မရှင်းလင်းသေးတဲ့နေရာတွေမှာ ကျွန်တော့်ရဲ့ အကောင်းဆုံးအလုပ်တွေ ဖြစ်ပေါ်လာပါတယ်။",
        "LLB ပညာရေးနောက်ခံက အထောက်အထားတွေကို စစ်ဆေးခြင်း၊ အကြောင်းပြချက်တွေကို စနစ်တကျတည်ဆောက်ခြင်းနဲ့ မရှင်းလင်းမှုတွေကြားကနေ အဖြေရှာခြင်းကို လေ့ကျင့်ပေးခဲ့ပါတယ်။ အခုအခါ အဲဒီစွမ်းရည်တွေကို product analysis၊ data systems၊ UX၊ automation နဲ့ applied AI မှာ အသုံးချနေပါတယ်။",
        "ရှင်းလင်းတဲ့ interface၊ ခန့်မှန်းချက်ထက် အထောက်အထားနဲ့ ဆက်လက်တိုးတက်အောင် ပြင်ဆင်နိုင်တဲ့ အသုံးဝင်သော ပထမဗားရှင်းတစ်ခု ထုတ်လုပ်ခြင်းကို ဦးစားပေးပါတယ်။",
      ],
    },
    experience: {
      label: "အတွေ့အကြုံနှင့် ပညာရေး",
      title: "Analysis နဲ့ product systems ဆီကို လက်တွေ့ကျကျ ရောက်လာခဲ့တဲ့ လမ်းကြောင်း။",
      intro: "ပညာရေး၊ လူတွေနဲ့တိုက်ရိုက်လုပ်ကိုင်ခဲ့တဲ့ အတွေ့အကြုံ၊ အတည်ပြုထားတဲ့ training နဲ့ ကိုယ်တိုင်နည်းပညာတည်ဆောက်မှုတွေက ပြဿနာတစ်ခုကို ကျွန်တော် ဘယ်လိုကိုင်တွယ်မလဲဆိုတာ ပုံဖော်ပေးခဲ့ပါတယ်။",
      items: [
        { year: "လက်ရှိ", role: "Independent product builder", org: "Wisp Guide", detail: "Product strategy၊ UX၊ analytics၊ AI integration၊ authentication၊ deployment နဲ့ commercial flow တွေကို တာဝန်ယူလုပ်ဆောင်နေပါတယ်။" },
        { year: "2026", role: "Python Data Associate", org: "DataCamp · Certified", detail: "DataCamp associate certification မှတစ်ဆင့် လက်တွေ့ Python နဲ့ data-handling အသိပညာကို အတည်ပြုထားပါတယ်။" },
        { year: "2023", role: "Field interviewer", org: "Myanmar Survey Research", detail: "လက်တွေ့ပတ်ဝန်းကျင်မှာ စနစ်တကျ response တွေ စုဆောင်းပြီး research participant တွေနဲ့ တိုက်ရိုက်လုပ်ကိုင်ခဲ့ပါတယ်။" },
        { year: "2018–19", role: "Customer service", org: "Byblos", detail: "ဆက်သွယ်ရေး၊ ဝန်ဆောင်မှုနဲ့ လူတွေ အမှန်တကယ်လိုအပ်တာကို နားလည်ခြင်းအတွက် အစောပိုင်းအခြေခံတစ်ခု တည်ဆောက်ခဲ့ပါတယ်။" },
      ],
      education: "ပညာရေး",
      degree: "LLB · ပြီးဆုံး",
      educationBody: "ဥပဒေပညာရေးက research၊ အထောက်အထားအကဲဖြတ်မှု၊ စနစ်တကျတွေးခေါ်မှုနဲ့ ဆက်သွယ်ရေးစွမ်းရည်တွေကို ခိုင်မာစေခဲ့ပါတယ်။",
      credential: "အတည်ပြုထားသော လက်မှတ် · JUNE 25, 2026",
      certificate: "Python Data Associate",
      certifiedBy: "DataCamp မှ အသိအမှတ်ပြု",
      viewCertificate: "လက်မှတ်ကို ကြည့်ရန်",
    },
    demos: {
      label: "လုပ်ငန်းသုံး ဝဘ်ဆိုဒ် နမူနာများ",
      title: "ပြည်တွင်းလုပ်ငန်းတွေအတွက် လက်တွေ့ကျတဲ့ website များ။",
      intro: "တစ်ခါသုံး mockup တွေမဟုတ်ပါ။ တစ်ခုစီကို brand ပြောင်းပြီး client website တစ်ခုအဖြစ် လျင်မြန်စွာ ပြင်ဆင်အသုံးပြုနိုင်ပါတယ်။",
      demoLabel: "CONCEPT / DEMO",
      viewConcept: "နမူနာကို ကြည့်ရန်",
      allExamples: "Website နမူနာအားလုံး ကြည့်ရန်",
      tags: ["Responsive", "Semantic HTML", "Metadata"],
      items: [
        { slug: "cafe", type: "ကဖေးလုပ်ငန်း", name: "Northstar Coffee", line: "Menu၊ တည်နေရာ၊ ဖွင့်ချိန်နဲ့ order flow ပါဝင်တဲ့ နွေးထွေးသော café website concept တစ်ခုပါ။", accent: "amber" },
        { slug: "restaurant", type: "စားသောက်ဆိုင်", name: "Serein Table", line: "စားသောက်ဆိုင်ကို ရှာဖွေသိရှိနိုင်ပြီး reservation လုပ်နိုင်ဖို့ တည်ဆောက်ထားတဲ့ editorial website experience တစ်ခုပါ။", accent: "coral" },
        { slug: "law-firm", type: "Professional services", name: "Aster & Rowe", line: "ဝန်ဆောင်မှု၊ team profile နဲ့ consultation လမ်းကြောင်းတွေပါဝင်တဲ့ တည်ငြိမ်ရှင်းလင်းသော ဥပဒေဝန်ဆောင်မှု website တစ်ခုပါ။", accent: "blue" },
        { slug: "shop", type: "ပြည်တွင်းအရောင်းဆိုင်", name: "Field Supply", line: "Product ရှာဖွေခြင်းနဲ့ တိုက်ရိုက်မှာယူခြင်းအတွက် တည်ဆောက်ထားတဲ့ local-shop catalogue တစ်ခုပါ။", accent: "green" },
      ],
    },
    services: {
      label: "ဝန်ဆောင်မှုများ",
      title: "လွတ်လပ်စွာ၊ လက်တွေ့ကျကျနဲ့ သင်အမှန်တကယ်လိုအပ်တာကို အခြေခံပြီး တည်ဆောက်ပေးပါတယ်။",
      intro: "အသေးစား team နဲ့ လုပ်ငန်းတွေကို ပြဿနာရှင်းလင်းသတ်မှတ်ခြင်း၊ digital experience တိုးတက်စေခြင်းနဲ့ အာရုံစိုက်ထားတဲ့ solution တစ်ခု ထုတ်လုပ်ခြင်းမှာ ကူညီပါတယ်။",
      items: ["Business website နှင့် landing page", "Website redesign နှင့် UX improvement", "Analytics dashboard နှင့် KPI design", "Business process နှင့် system analysis", "AI အကူအညီသုံး solution", "ပေါ့ပါးသော automation"],
      viewAll: "Freelance website ဝန်ဆောင်မှုများ ကြည့်ရန်",
    },
    contact: {
      label: "ဆက်သွယ်ရန်",
      title: "Analyst နဲ့ product အလုပ်အကိုင်အခွင့်အလမ်းများအတွက် လက်ခံနေပါသည်။",
      candidateLabel: "အလုပ်ခန့်ရန် ရှာဖွေနေပါသလား?",
      candidateTitle: "လုပ်ဆောင်မှုနဲ့ အထောက်အထားတွေကို ကြည့်ပါ။",
      body: "ရန်ကုန် သို့မဟုတ် remote မှ Junior Business Analyst၊ Data Analyst၊ Product Analyst နဲ့ အာရုံစိုက်ထားတဲ့ automation အလုပ်အကိုင်များကို လက်ခံနေပါတယ်။",
      clientLabel: "WEBSITE သို့မဟုတ် AUTOMATION လိုအပ်ပါသလား?",
      clientTitle: "သင့် project အကြောင်း ပြောပြပါ။",
      clientBody: "Freelance အတွက် website အသစ်၊ website redesign၊ landing page သို့မဟုတ် automation project အသေးစားများကို ဆက်သွယ်မေးမြန်းနိုင်ပါတယ်။",
      email: "အီးမေးလ်ပို့ရန်",
      viewWork: "လုပ်ဆောင်မှုများ ကြည့်ရန်",
      discussProject: "Project ဆွေးနွေးရန်",
      viewServices: "ဝန်ဆောင်မှုများ ကြည့်ရန်",
      cv: "CV ရယူရန်",
      footerRole: "Data Analyst · Automation Engineer · Product Builder",
    },
  },
} as const;
